name: lint

on: [push, pull_request]

jobs:
  lint:
    name: Run linters

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup Node.js 24.x
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
          cache: 'npm'

      - name: Touch cli file to prevent npm ci from freaking out
        uses: DamianReeves/write-file-action@v1.3
        with:
          path: packages/html-to-text-cli/bin/cli.js
          contents: '// placeholder'

      - run: npm ci

      - run: npm run lint
