name: test

on: [push, pull_request]

jobs:
  test:
    name: Run tests

    strategy:
      matrix:
        node-version: [20.x, 24.x]
        os: [ubuntu-latest, windows-latest]
        include:
          - os: windows-latest
            get-cache-path: '"dir=$(npm config get cache)" >> $env:GITHUB_OUTPUT'
          - os: ubuntu-latest
            get-cache-path: 'echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT'

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Touch cli file to prevent npm ci from freaking out
        uses: DamianReeves/write-file-action@v1.3
        with:
          path: packages/html-to-text-cli/bin/cli.js
          contents: '// placeholder'

      - run: npm ci

      - run: npm test
